include:
  - project: 'dependabot-gitlab/dependabot-standalone'
    file: '.gitlab-ci.yml'

image: node:latest

stages:
  - deploy
  - dependabot

# allow caching for faster deployment
cache:
  paths:
    - node_modules/
    - public/
    - .cache/

pages:
  stage: deploy
  script:
    - npm install
    - npm run write-translations
    - npm run write-translations -- --locale de
    - npm run build:gitlab
  artifacts:
      paths:
        - public
  only:
    - main

.dependabot-gitlab:
  stage: dependabot
