include:
  - project: 'dependabot-gitlab/dependabot-standalone'
    file: '.gitlab-ci.yml'

image: node:latest

stages:
  - dependabot
  - deploy

# allow caching for faster deployment
cache:
  paths:
    - node_modules/
    - public/
    - .cache/

pages:
  stage: deploy
  script:
    - npm install
    - npm run write-translations
    - npm run crowdin:sync
    - npm run build:gitlab
  artifacts:
      paths:
        - public

.dependabot-gitlab:
  stage: dependabot
